# Generated by Django 2.2.9 on 2019-12-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moedaCorrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(max_length=5)),
                ('codigo', models.CharField(default='BRL', max_length=5)),
            ],
        ),
    ]
